// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// delta_SEIR_cpp
NumericVector delta_SEIR_cpp(NumericVector event);
RcppExport SEXP _movingModelRcpp_delta_SEIR_cpp(SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type event(eventSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_SEIR_cpp(event));
    return rcpp_result_gen;
END_RCPP
}
// event_rate_coloc_cpp
NumericVector event_rate_coloc_cpp(NumericVector SEIR_vector, int numpatch, float Di, float De, NumericMatrix R0_matrix, IntegerVector N);
RcppExport SEXP _movingModelRcpp_event_rate_coloc_cpp(SEXP SEIR_vectorSEXP, SEXP numpatchSEXP, SEXP DiSEXP, SEXP DeSEXP, SEXP R0_matrixSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type SEIR_vector(SEIR_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type numpatch(numpatchSEXP);
    Rcpp::traits::input_parameter< float >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< float >::type De(DeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R0_matrix(R0_matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(event_rate_coloc_cpp(SEIR_vector, numpatch, Di, De, R0_matrix, N));
    return rcpp_result_gen;
END_RCPP
}
// event_rate_move_cpp
NumericVector event_rate_move_cpp(NumericVector SEIR_vector, int numpatch, float Di, float De, NumericVector R0, IntegerVector N, NumericMatrix P);
RcppExport SEXP _movingModelRcpp_event_rate_move_cpp(SEXP SEIR_vectorSEXP, SEXP numpatchSEXP, SEXP DiSEXP, SEXP DeSEXP, SEXP R0SEXP, SEXP NSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type SEIR_vector(SEIR_vectorSEXP);
    Rcpp::traits::input_parameter< int >::type numpatch(numpatchSEXP);
    Rcpp::traits::input_parameter< float >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< float >::type De(DeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(event_rate_move_cpp(SEIR_vector, numpatch, Di, De, R0, N, P));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_movingModelRcpp_delta_SEIR_cpp", (DL_FUNC) &_movingModelRcpp_delta_SEIR_cpp, 1},
    {"_movingModelRcpp_event_rate_coloc_cpp", (DL_FUNC) &_movingModelRcpp_event_rate_coloc_cpp, 6},
    {"_movingModelRcpp_event_rate_move_cpp", (DL_FUNC) &_movingModelRcpp_event_rate_move_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_movingModelRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
