# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the SEIR change based on the event rate.
#' 
#' @param event The numeric vector from event_rate function.
#' @return A vector of SEIR change.
delta_SEIR_cpp <- function(event) {
    .Call(`_movingModelRcpp_delta_SEIR_cpp`, event)
}

#' Calculate the event rate of contact model based on SEIR vector.
#' 
#' @param SEIR_vector The numeric vector of current SEIR status.
#' @param numpatch length of location list.
#' @param Di The duration of infectious period (days).
#' @param De The duration of exposed period (days).
#' @param R0_matrix The matrix of R0 between two locations.
#' @param N The vector of population at each location.
#' @return A vector of event rate.
event_rate_coloc_cpp <- function(SEIR_vector, numpatch, Di, De, R0_matrix, N) {
    .Call(`_movingModelRcpp_event_rate_coloc_cpp`, SEIR_vector, numpatch, Di, De, R0_matrix, N)
}

#' Calculate the event rate of residence model based on SEIR vector.
#' 
#' @param SEIR_vector The numeric vector of current SEIR status.
#' @param numpatch length of location list.
#' @param Di The duration of infectious period (days).
#' @param De The duration of exposed period (days).
#' @param R0 The vector of R0 in each location.
#' @param N The vector of population at each location.
#' @param P The matrix of possibility that a resident in location i move to locaiton j in a unit of time.
#' @return A vector of event rate.
event_rate_move_cpp <- function(SEIR_vector, numpatch, Di, De, R0, N, P) {
    .Call(`_movingModelRcpp_event_rate_move_cpp`, SEIR_vector, numpatch, Di, De, R0, N, P)
}

